{
	"version": 1665574860,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/cartero-sheet0.png",
		"images/personajes-sheet0.png",
		"images/personajes-sheet1.png",
		"images/personajes-sheet2.png",
		"images/carta-sheet0.png",
		"images/carteroimg-sheet0.png",
		"images/solid-sheet0.png",
		"images/runningparticles.png",
		"images/obstaculogenerado-sheet0.png",
		"images/obstaculogenerado-sheet1.png",
		"images/indicadordestinatario-sheet0.png",
		"images/indicadordestinatario-sheet1.png",
		"images/barratiempofondo-sheet0.png",
		"images/barratiempo-sheet0.png",
		"images/iconoreloj-sheet0.png",
		"images/bgtilemap.png",
		"images/shadowplayer-sheet0.png",
		"images/fondoimage-sheet0.png",
		"images/puntostxt.png",
		"images/puntostxtborder.png",
		"images/fondoresults-sheet0.png",
		"images/uibuttons-sheet0.png",
		"images/uibuttons-sheet1.png",
		"images/transition-sheet0.png",
		"images/gameovertxt-sheet0.png",
		"images/fondomenuinicio-sheet0.png",
		"images/nubemenuinicio-sheet0.png",
		"images/gametitle-sheet0.png",
		"images/subrayadoinstrucciones-sheet0.png",
		"images/instruccionesimgs-sheet0.png",
		"images/cuadradosgiratoriosinstrucciones-sheet0.png",
		"images/pausabackground-sheet0.png",
		"images/pausaactivator-sheet0.png",
		"media/coger carta.m4a",
		"media/coger carta.ogg",
		"media/envia carta.m4a",
		"media/envia carta.ogg",
		"media/música cartas marruecas.m4a",
		"media/música cartas marruecas.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}